[tool.basedpyright]
include = ["dags", "mwaa_public"]
exclude = ["**/node_modules",
    "**/__pycache__",
]
defineConstant = { DEBUG = true }
venvPath = "./"
venv = "venv"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "Darwin"
